fix: get tests passing!
Two big changes:

1) use `happy-dom` environment rather than `js-dom` or our custom environment. A new, strange incompatibility between the crypto API `@noble/ed25519` expects and what `webcrypto` provides seems to be a problem after upgrading `vitest`, ie:

```
 RUN  v1.0.1 /Users/travis/dev/pl/w3ui/packages/core

 ❯ test/client.spec.ts (2)
   × createClient
   × createSpace

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/client.spec.ts > createClient
 FAIL  test/client.spec.ts > createSpace
TypeError: Failed to execute 'digest' on 'SubtleCrypto': 2nd argument is not instance of ArrayBuffer, Buffer, TypedArray, or DataView.
 ❯ Object.sha512 ../../node_modules/.pnpm/@noble+ed25519@1.7.3/node_modules/@noble/ed25519/lib/esm/index.js:860:52
 ❯ getExtendedPublicKey ../../node_modules/.pnpm/@noble+ed25519@1.7.3/node_modules/@noble/ed25519/lib/esm/index.js:674:39
 ❯ Module.getPublicKey ../../node_modules/.pnpm/@noble+ed25519@1.7.3/node_modules/@noble/ed25519/lib/esm/index.js:680:19
 ❯ derive ../../node_modules/.pnpm/@ucanto+principal@9.0.0/node_modules/@ucanto/principal/src/ed25519/signer.js:42:35
 ❯ generate ../../node_modules/.pnpm/@ucanto+principal@9.0.0/node_modules/@ucanto/principal/src/ed25519/signer.js:28:31
 ❯ Module.create ../../node_modules/.pnpm/@web3-storage+w3up-client@11.2.0/node_modules/@web3-storage/w3up-client/src/index.node.js:38:49
 ```

 This seems to go away entirely when using `happy-dom`, which means we can also get rid of our custom vitest environment. Win!

 2) Stop using `@testing-library/react-hooks` - it looks like I missed the fact that it's been deprecated!

https://github.com/testing-library/react-hooks-testing-library/tree/main#a-note-about-react-18-support

The new API in `@testing-library/react` is just a little different, so I've updated the tests accordingly.